# Generated by Django 3.0.8 on 2020-09-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('event_name', models.CharField(max_length=250)),
                ('due_date', models.DateField(verbose_name='date published')),
                ('description', models.CharField(max_length=500)),
                ('importance', models.IntegerField(default=0)),
                ('urgency', models.IntegerField(default=0)),
                ('approx_time', models.IntegerField(default=0)),
                ('completion', models.IntegerField(default=0)),
                ('parent_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
