# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_auto_20160702_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approx_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='completion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='due_date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='event',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='urgency',
            field=models.IntegerField(default=0),
        ),
    ]
