# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_auto_20160702_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.AddField(
            model_name='event',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
